# Generated by Django 5.2 on 2025-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megatrend', models.CharField(max_length=150)),
                ('macrotrend', models.CharField(max_length=200)),
                ('challenges_and_research_gaps', models.TextField()),
                ('total_count_of_publications', models.IntegerField(blank=True, null=True)),
                ('total_count_of_patents', models.IntegerField(blank=True, null=True)),
                ('technology_readiness_level', models.CharField(blank=True, choices=[('Pilot', 'Pilot'), ('Development', 'Development'), ('Deploy', 'Deploy')], max_length=50, null=True)),
                ('impact_strength', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=('Low', 'Low'), max_length=50)),
                ('steepl', models.CharField(choices=[('S', 'S'), ('T', 'T'), ('E', 'E'), ('P', 'P'), ('L', 'L')], default=('S', 'S'), max_length=10)),
                ('relevant_industries', models.TextField(blank=True, null=True)),
                ('real_world_application_and_use_cases', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
