# Generated by Django 5.1.8 on 2025-04-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='total_count_of_patents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='total_count_of_publications',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
